server:
  port: 8080
  servlet:
    context-path: /mac-donation

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: MAC-Donations

maccourses:
  jwt:
    expiracao: 7200000
    secret: "DE2EDBCE3E86603316B9C03AB2ABAECE1AA3551CD76338732E8371EE5D1355D3"